### ISSUE TITLE
Some IC2 textures downloaded as HTML instead of PNG

### ISSUE THREAD

**Issue by Kilmatar** [Soartex/Texture-Patcher-v1#47]
# Using latest patcher i was trying to update textures. After successfull update my Minecraft starts crashing:

java.lang.NullPointerException
    at bba.b(RenderEngine.java:227)
    at bba.a(RenderEngine.java:208)
    at ic2.core.util.TextureIndexClient.get(TextureIndexClient.java:20)
    at ic2.core.block.TileEntityBlock.onNetworkUpdate(TileEntityBlock.java:170)
    at ic2.core.network.NetworkManagerClient.onPacketData(NetworkManagerClient.java:262)
    at cpw.mods.fml.common.network.NetworkRegistry.handlePacket(NetworkRegistry.java:243)
    at cpw.mods.fml.common.network.NetworkRegistry.handleCustomPacket(NetworkRegistry.java:233)
    at cpw.mods.fml.common.network.FMLNetworkHandler.handlePacket250Packet(FMLNetworkHandler.java:71)
    at ayh.a(NetClientHandler.java:1483)
    at di.a(SourceFile:59)
    at com.mumfrey.liteloader.core.HookPluginChannels.a(HookPluginChannels.java:99)
    at cg.b(TcpConnection.java:458)
    at ayh.d(NetClientHandler.java:240)
    at ayp.b(WorldClient.java:92)
    at net.minecraft.client.Minecraft.l(Minecraft.java:1874)
    at net.minecraft.client.Minecraft.J(Minecraft.java:848)
    at net.minecraft.client.Minecraft.run(Minecraft.java:773)
#     at java.lang.Thread.run(Unknown Source)

As i can see - problem was caused by IC2 texture.
After some experiments with manual files replacing i found 5 texture files that was causing problem:
block_generator.png,
item_0.png,
block_electric.png,
block_machine2.png,
block_personal.png

I was try to open this files in graphic viewer with no result. After that i open this files in text editor and voila! This files was contain HTML code! I can't copy text of HTML but that was GitHub's HTML.

Suggestion: check data format of downloaded files - is it REAL PNG or NOT? =)

**Comment by goldbattle** [comment]
This has been fixed, forgot to reply here to let you know that is has been.
